font:
  normal:
    family: Iosevka Nerd Font Mono
    style: Light
  size: 14.0

bell:
  animation: EaseOutExpo
  color: '#ffffff'
background_opacity: 0.97

selection:
  save_to_clipboard: true

cursor:
  style: Block
  vi_mode_style: Block
  unfocused_hollow: true

live_config_reload: true

shell:
  program: /bin/zsh
  args:
    - --login

window:
  decorations: none

colors:
  # Default colors
  primary:
    background: '0xeeeeee'
    foreground: '0x4d4d4c'

  # Colors the cursor will use if `custom_cursor_colors` is true
  cursor:
    text: '0xf3f3f3'
    cursor: '0x4d4d4c'

  # Normal colors
  normal:
    black:   '0xededed'
    red:     '0xd7005f'
    green:   '0x718c00'
    yellow:  '0xd75f00'
    blue:    '0x4271ae'
    magenta: '0x8959a8'
    cyan:    '0x3e999f'
    white:   '0x4d4d4c'

  # Bright colors
  bright:
    black:   '0x949494'
    red:     '0xd7005f'
    green:   '0x718c00'
    yellow:  '0xd75f00'
    blue:    '0x4271ae'
    magenta: '0x8959a8'
    cyan:    '0x3e999f'
    white:   '0xf5f5f5'
