#!/bin/bash
set -e

zsh_file="$HOME/.zshrc"
zsh_theme_file="$HOME/.oh-my-zsh/custom/themes/ds.zsh-theme"
zsh_lang_file="$HOME/zsh/lang.sh"
zsh_work_file="$HOME/zsh/work.sh"
zsh_completions="$HOME/zsh/completions"

nvim_file="$HOME/.config/nvim/init.vim"
vim_pres_file="$HOME/.config/nvim/presentation.vim"
coc_settings_file="$HOME/.config/nvim/coc-settings.json"
ccls_file="$HOME/.config/nvim/default_ccls"
extras="$HOME/.config/nvim/extras"

tmux_file="$HOME/.tmux.conf"
alacritty_file="$HOME/.alacritty.yml"

install() {
  echo "-> Getting latest updates from GitHub"
  git pull
  if [ ! -d "$HOME/zsh" ]; then
      mkdir $HOME/zsh
  fi
  if [ ! -d "$HOME/zsh/completions" ]; then
      mkdir $HOME/zsh/completions
  fi
  echo "-> Copying configuration files"
  cat zsh/.zshrc > $zsh_file
  cp zsh/ds.zsh-theme "$HOME/.oh-my-zsh/custom/themes/"
  cp zsh/lang.sh $HOME/zsh/
  cp zsh/work.sh $HOME/zsh/
  cp -r zsh/completions/ $HOME/zsh/completions
  cat vim/init.vim > $nvim_file
  cp vim/presentation.vim "$HOME/.config/nvim/"
  cp vim/coc-settings.json "$HOME/.config/nvim/"
  cp tmux/.tmux.conf "$HOME/.tmux.conf"
  cp alacritty/.alacritty.yml "$HOME/.alacritty.yml" 
  cp vim/ccls_file "$HOME/.config/nvim/"
  cp vim/extras "$HOME/.config/nvim/"
  echo "-> Done"
}

upload() {
  echo "-> Copying configuration files"
  cp $zsh_file zsh/
  cp $zsh_theme_file zsh/
  cp $zsh_lang_file zsh/
  cp $zsh_work_file zsh/
  cp -r $zsh_completions zsh/completions
  cp $nvim_file vim/
  cp $vim_pres_file vim/
  cp $coc_settings_file vim/
  cp $ccls_file vim/
  cp $extras vim/
  cp $tmux_file tmux/
  cp $alacritty_file alacritty/
  git add -A && git commit -m "Dotfiles synced on $(date +%Y-%m-%d)" && git push
}

print_help() {
  echo "Hey there."
  echo "    This run script requires an arg of either 'install' or 'upload'"
  echo "    -> install: Overwrites your local configs with those at the latest pull of this branch"
  echo "    -> upload: Copies your local configs into this dir and pushes them to the branch"
}

case $1 in
  "install")
    install
    ;;
  "upload")
    upload
    ;;
  *)
    print_help
    ;;
esac
